### ISSUE TITLE
Mimimum version of cudatoolkit and pytorch

### ISSUE THREAD

**Issue by Mikerov** [matteo-ronchetti/torch-radon#20]
What are the minimum possible versions of pytorch and cudatoolkit when building from source.

I receive a lot of errors when building using Pytorch 1.1 and cudatoolkit 9.0, which I don't have for Pytorch 1.7 and cudatoolkit 10.

Due to hardware restrictions it is not possible for me to install newer versions. Does it mean that it is hopeless?

**Comment by matteo-ronchetti** [comment]
I think you should compile PyTorch from source (as explained [here](https://github.com/pytorch/pytorch#from-source)) in order to get a new version of PyTorch working with CUDA 9. Then you should be able to install TorchRadon from source as explained [here](https://github.com/matteo-ronchetti/torch-radon#build-from-source).

**Comment by Mikerov** [comment]
Building PyTorch from source seems to have solved the issue
